# Generated by Django 2.2.12 on 2020-05-25 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('icon', models.ImageField(default='', upload_to='images/')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('pub_date', models.DateTimeField(default='')),
                ('votes_total', models.IntegerField(default=0)),
                ('hunter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
